// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0KewttPZAkOlRTQQVoc_n64nprY2vgvY',
    appId: '1:993121206813:web:5e573e7afb0b5a85217cf4',
    messagingSenderId: '993121206813',
    projectId: 'zenzith-a4145',
    authDomain: 'zenzith-a4145.firebaseapp.com',
    storageBucket: 'zenzith-a4145.appspot.com',
    measurementId: 'G-NEKN02LLCG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhPobtqNUX0E3udTNehJwXCbrSBEombyc',
    appId: '1:993121206813:android:c8a5e618b563e2e0217cf4',
    messagingSenderId: '993121206813',
    projectId: 'zenzith-a4145',
    storageBucket: 'zenzith-a4145.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSmokKaV_L1yADMYLioS-EEttRRvkm0yk',
    appId: '1:993121206813:ios:7c451116cd5102b3217cf4',
    messagingSenderId: '993121206813',
    projectId: 'zenzith-a4145',
    storageBucket: 'zenzith-a4145.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSmokKaV_L1yADMYLioS-EEttRRvkm0yk',
    appId: '1:993121206813:ios:7c451116cd5102b3217cf4',
    messagingSenderId: '993121206813',
    projectId: 'zenzith-a4145',
    storageBucket: 'zenzith-a4145.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0KewttPZAkOlRTQQVoc_n64nprY2vgvY',
    appId: '1:993121206813:web:1c650e653425c0da217cf4',
    messagingSenderId: '993121206813',
    projectId: 'zenzith-a4145',
    authDomain: 'zenzith-a4145.firebaseapp.com',
    storageBucket: 'zenzith-a4145.appspot.com',
    measurementId: 'G-LS7KJTNS7C',
  );

}